ae = "${{inputs.flux_weights}}/ae.safetensors"
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
clip_l = "${{inputs.flux_weights}}/clip_l.safetensors"
discrete_flow_shift = 3.1582
dynamo_backend = "no"
epoch = 2
full_bf16 = true
gradient_accumulation_steps = 1
guidance_scale = 1.0
highvram = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
learning_rate = 0.00025
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
mem_eff_save = true
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 16
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_dim = 16
network_module = "networks.lora_flux"
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "Adafactor"
output_dir = "${{outputs.ModelSaves}}"
output_name = "Quality_Tier_3"
pretrained_model_name_or_path = "${{inputs.flux_weights}}/flux1-dev.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_sampler = "euler_a"
save_every_n_epochs = 20
save_model_as = "safetensors"
save_precision = "float"
seed = 1
skip_cache_check = true
t5xxl = "${{inputs.flux_weights}}/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = [ 0.00025, 0.00025,]
timestep_sampling = "sigmoid"
train_batch_size = 1
train_data_dir = "${{inputs.train_data}}"
unet_lr = 0.00025
vae_batch_size = 4
wandb_run_name = "Quality_Tier_3"
xformers = true
